In [6]:
from utils import read_json_zst, split_dataframe

data = read_json_zst("../data/training/0_0pct_faults_rep_1.json.zst", max_samples=1000)

In [8]:
data.columns.to_series().to_csv("columns.txt", index=False, header=False)

In [1]:

split_dataframe(data, "../data/training/0_0pct_faults_rep_1")

Regular dataframe shape: (1000, 1004)
Faults dataframe shape: (1000, 1372)
Parameters dataframe shape: (1000, 2173)
PR_118.X.CurrentForce
['<0. 0. -0>' '<12,122512. 0. -6,105615E-05>'
 '<12,12289. 0. -6,1058054E-05>' '<12,122895. 0. -6,1058076E-05>'
 '<71,44094. 0. -0,00035981886>' '<-0,6938273. -0. 3,494525E-06>'
 '<-12,111927. -0. 6,1002836E-05>' '<-11,779486. -0. 5,9328464E-05>'
 '<11,832959. 0. -5,9597787E-05>' '<11,777772. 0. -5,931983E-05>'
 '<12,426719. 0. -6,258831E-05>' '<31,190168. 0. -0,00015709216>'
 '<11,816452. 0. -5,951465E-05>' '<12,426739. 0. -6,258841E-05>'
 '<11,832941. 0. -5,9597696E-05>' '<-12,426976. -0. 6,258961E-05>'
 '<12,371595. 0. -6,2310675E-05>' '<11,777806. 0. -5,9320006E-05>'
 '<-12,426975. -0. 6,258961E-05>' '<-12,426968. -0. 6,258956E-05>'
 '<11,724466. 0. -5,9051352E-05>' '<11,777826. 0. -5,9320108E-05>'
 '<-12,427095. -0. 6,259021E-05>' '<11,724592. 0. -5,905199E-05>'
 '<11,777932. 0. -5,932064E-05>' '<-11,779841. -0. 5,9330254E-05>'
 '<11,724595. 0. -5,9052003E-05>' '<11,777931. 0. -5,9320635E-05>'
 '<-11,779942. -0. 5,933076E-05>' '<11,779577. 0. -5,9328926E-05>'
 '<-11,779822. -0. 5,933016E-05>' '<11,778044. 0. -5,9321203E-05>'
 '<11,777965. 0. -5,9320802E-05>' '<-11,779997. -0. 5,933104E-05>'
 '<11,777974. 0. -5,932085E-05>' '<12,4268675. 0. -6,258906E-05>'
 '<11,778046. 0. -5,932121E-05>' '<11,777879. 0. -5,932037E-05>'
 '<-12,426913. -0. 6,258929E-05>' '<12,426649. 0. -6,258796E-05>'
 '<11,777756. 0. -5,931975E-05>' '<-12,426905. -0. 6,258925E-05>'
 '<11,77952. 0. -5,9328635E-05>' '<11,777757. 0. -5,9319755E-05>'
 '<-12,426858. -0. 6,258902E-05>' '<11,779454. 0. -5,9328304E-05>'
 '<11,777691. 0. -5,9319424E-05>' '<-11,779603. -0. 5,9329053E-05>'
 '<11,779457. 0. -5,932832E-05>' '<11,77769. 0. -5,931942E-05>'
 '<-11,7796955. -0. 5,932952E-05>' '<11,834457. 0. -5,9605332E-05>'
 '<11,722706. 0. -5,9042486E-05>' '<-11,779689. -0. 5,9329486E-05>'
 '<11,832939. 0. -5,9597685E-05>' '<11,7227545. 0. -5,9042733E-05>'
 '<-11,77971. -0. 5,932959E-05>' '<12,426645. 0. -6,258794E-05>'
 '<11,83294. 0. -5,9597693E-05>' '<11,722764. 0. -5,904278E-05>'
 '<-12,427103. -0. 6,259025E-05>' '<12,426766. 0. -6,258855E-05>'
 '<11,832913. 0. -5,9597558E-05>' '<11,779636. 0. -5,9329224E-05>'
 '<11,832915. 0. -5,9597565E-05>' '<-12,4271555. -0. 6,2590516E-05>'
 '<11,77967. 0. -5,932939E-05>' '<11,832948. 0. -5,959773E-05>'
 '<-11,779902. -0. 5,9330563E-05>' '<11,7246275. 0. -5,9052167E-05>'
 '<11,777964. 0. -5,93208E-05>' '<11,722921. 0. -5,9043574E-05>'
 '<11,777825. 0. -5,93201E-05>' '<-11,779743. -0. 5,932976E-05>'
 '<12,426594. 0. -6,2587686E-05>' '<11,722923. 0. -5,904358E-05>'
 '<11,777835. 0. -5,9320148E-05>' '<12,426729. 0. -6,258836E-05>'
 '<11,778015. 0. -5,9321057E-05>' '<-12,426966. -0. 6,2589555E-05>'
 '<12,426667. 0. -6,258806E-05>' '<-12,426965. -0. 6,258955E-05>'
 '<11,779539. 0. -5,9328733E-05>' '<-12,426967. -0. 6,258956E-05>'
 '<11,779587. 0. -5,9328973E-05>' '<11,777739. 0. -5,9319664E-05>'
 '<-11,779615. -0. 5,932912E-05>' '<11,779504. 0. -5,9328555E-05>'
 '<11,777737. 0. -5,9319653E-05>' '<-11,779614. -0. 5,932911E-05>'
 '<11,778063. 0. -5,9321297E-05>' '<11,777863. 0. -5,932029E-05>'
 '<-11,7797365. -0. 5,9329726E-05>' '<12,426634. 0. -6,258788E-05>'
 '<11,778082. 0. -5,932139E-05>' '<11,778009. 0. -5,9321028E-05>'
 '<12,426635. 0. -6,258789E-05>' '<11,777937. 0. -5,9320664E-05>'
 '<11,778042. 0. -5,932119E-05>' '<12,426668. 0. -6,258806E-05>'
 '<-12,427263. -0. 6,2591054E-05>' '<12,426672. 0. -6,258808E-05>'
 '<11,779541. 0. -5,9328744E-05>' '<11,777966. 0. -5,9320806E-05>'
 '<-12,427075. -0. 6,259011E-05>' '<11,834514. 0. -5,9605616E-05>'
 '<-12,427101. -0. 6,259024E-05>' '<11,777688. 0. -5,931941E-05>'
 '<-11,779849. -0. 5,9330294E-05>' '<11,834517. 0. -5,960563E-05>'
 '<11,832885. 0. -5,9597412E-05>' '<11,777623. 0. -5,931908E-05>'
 '<-11,779797. -0. 5,933003E-05>' '<-11,724722. -0. 5,905264E-05>'
 '<11,777975. 0. -5,9320857E-05>' '<11,777633. 0. -5,9319133E-05>'
 '<12,371545. 0. -6,231042E-05>' '<11,777977. 0. -5,9320864E-05>'
 '<11,777678. 0. -5,9319358E-05>' '<12,3715925. 0. -6,231066E-05>'
 '<11,777874. 0. -5,9320348E-05>' '<-12,426878. -0. 6,258911E-05>'
 '<12,371596. 0. -6,231068E-05>' '<11,724467. 0. -5,905136E-05>'
 '<11,777875. 0. -5,932035E-05>' '<-12,481943. -0. 6,286646E-05>'
 '<11,778. 0. -5,932098E-05>' '<-12,48207. -0. 6,28671E-05>'
 '<11,777998. 0. -5,932097E-05>' '<-11,834816. -0. 5,960714E-05>'
 '<11,722883. 0. -5,904338E-05>' '<11,778031. 0. -5,9321137E-05>'
 '<-11,834872. -0. 5,9607424E-05>' '<11,723062. 0. -5,904428E-05>'
 '<-11,7797985. -0. 5,933004E-05>' '<11,778095. 0. -5,932146E-05>'
 '<11,777905. 0. -5,9320504E-05>' '<11,778097. 0. -5,932147E-05>'
 '<12,426528. 0. -6,258735E-05>' '<11,777807. 0. -5,932001E-05>'
 '<-12,42701. -0. 6,258978E-05>' '<12,426532. 0. -6,258737E-05>'
 '<11,777824. 0. -5,9320097E-05>' '<11,779336. 0. -5,932771E-05>'
 '<11,7777605. 0. -5,9319776E-05>' '<-12,427054. -0. 6,259001E-05>'
 '<11,777759. 0. -5,9319766E-05>' '<-11,779801. -0. 5,9330054E-05>'
 '<11,779339. 0. -5,9327725E-05>' '<11,779347. 0. -5,932777E-05>'
 '<-11,779809. -0. 5,9330094E-05>' '<11,8329315. 0. -5,959765E-05>'
 '<11,777671. 0. -5,931932E-05>' '<11,77768. 0. -5,9319373E-05>'
 '<12,42671. 0. -6,258827E-05>' '<11,832933. 0. -5,959766E-05>'
 '<11,7776985. 0. -5,9319464E-05>' '<12,426835. 0. -6,25889E-05>'
 '<11,832907. 0. -5,9597525E-05>' '<-12,427005. -0. 6,258975E-05>'
 '<12,426839. 0. -6,2588915E-05>' '<12,371722. 0. -6,2311316E-05>'
 '<11,777999. 0. -5,9320977E-05>' '<-12,426997. -0. 6,2589716E-05>'
 '<11,724625. 0. -5,9052152E-05>' '<11,778032. 0. -5,9321144E-05>'
 '<-12,427058. -0. 6,259002E-05>' '<11,77803. 0. -5,9321133E-05>'
 '<-11,779803. -0. 5,9330065E-05>' '<11,777892. 0. -5,932044E-05>'
 '<-11,834719. -0. 5,960665E-05>' '<11,777903. 0. -5,932049E-05>'
 '<12,481647. 0. -6,2864965E-05>' '<11,778011. 0. -5,932104E-05>'
 '<12,481581. 0. -6,286463E-05>' '<11,722857. 0. -5,904325E-05>'
 '<-12,427063. -0. 6,259004E-05>' '<12,481585. 0. -6,286465E-05>'
 '<11,777605. 0. -5,931899E-05>' '<-12,371988. -0. 6,2312654E-05>'
 '<-12,371981. -0. 6,231262E-05>' '<11,8345. 0. -5,960555E-05>'
 '<11,777654. 0. -5,9319238E-05>' '<-12,371993. -0. 6,231268E-05>'
 '<11,834503. 0. -5,9605565E-05>' '<-11,72474. -0. 5,905273E-05>'
 '<11,834505. 0. -5,9605572E-05>' '<11,777652. 0. -5,9319227E-05>'
 '<-11,724739. -0. 5,9052727E-05>' '<11,779523. 0. -5,932865E-05>'
 '<-11,724862. -0. 5,9053345E-05>' '<11,778081. 0. -5,9321388E-05>'
 '<11,832914. 0. -5,959756E-05>' '<12,371717. 0. -6,2311294E-05>'
 '<11,778083. 0. -5,93214E-05>' '<11,83278. 0. -5,9596885E-05>'
 '<12,37175. 0. -6,2311454E-05>' '<11,778115. 0. -5,9321563E-05>'
 '<-12,48214. -0. 6,2867446E-05>' '<12,426737. 0. -6,2588406E-05>'
 '<11,777957. 0. -5,9320762E-05>' '<-12,482131. -0. 6,28674E-05>'
 '<11,779608. 0. -5,932908E-05>' '<11,77782. 0. -5,932007E-05>'
 '<-12,481977. -0. 6,286663E-05>' '<11,779469. 0. -5,9328377E-05>'
 '<11,777819. 0. -5,9320068E-05>' '<-11,834724. -0. 5,960668E-05>'
 '<11,779471. 0. -5,932839E-05>' '<11,722772. 0. -5,9042817E-05>'
 '<-11,77975. -0. 5,9329795E-05>' '<11,722881. 0. -5,904337E-05>'
 '<-11,779697. -0. 5,932953E-05>' '<11,77784. 0. -5,9320173E-05>'
 '<11,722707. 0. -5,9042493E-05>' '<12,426597. 0. -6,25877E-05>'
 '<11,777842. 0. -5,9320184E-05>' '<11,722717. 0. -5,9042544E-05>'
 '<12,426641. 0. -6,2587926E-05>' '<11,777888. 0. -5,9320417E-05>'
 '<-12,372002. -0. 6,231273E-05>' '<12,481632. 0. -6,286489E-05>'
 '<-12,427074. -0. 6,25901E-05>' '<12,481631. 0. -6,2864885E-05>'
 '<11,834502. 0. -5,9605558E-05>' '<-12,427195. -0. 6,259071E-05>'
 '<11,834626. 0. -5,9606184E-05>' '<-11,7799425. -0. 5,9330763E-05>'
 '<11,834629. 0. -5,96062E-05>' '<11,777777. 0. -5,9319857E-05>'
 '<-11,724868. -0. 5,9053375E-05>' '<11,777632. 0. -5,9319125E-05>'
 '<-11,724928. -0. 5,905368E-05>' '<11,833096. 0. -5,9598475E-05>'
 '<11,77781. 0. -5,9320024E-05>' '<-11,724923. -0. 5,9053655E-05>'
 '<11,8330965. 0. -5,959848E-05>' '<11,833097. 0. -5,9598486E-05>'
 '<11,777821. 0. -5,932008E-05>' '<12,371583. 0. -6,231062E-05>'
 '<11,777976. 0. -5,932086E-05>' '<11,832819. 0. -5,959708E-05>'
 '<12,371611. 0. -6,2310755E-05>' '<-12,481986. -0. 6,2866675E-05>'
 '<12,371614. 0. -6,231078E-05>' '<11,724484. 0. -5,9051446E-05>'
 '<11,777761. 0. -5,931978E-05>' '<-12,481931. -0. 6,286639E-05>'
 '<11,72442. 0. -5,905112E-05>' '<-11,834678. -0. 5,9606442E-05>'
 '<11,779406. 0. -5,932806E-05>' '<11,777752. 0. -5,9319733E-05>'
 '<-11,834677. -0. 5,960644E-05>' '<-11,834689. -0. 5,96065E-05>'
 '<11,777886. 0. -5,932041E-05>' '<11,7778. 0. -5,9319973E-05>'
 '<-11,834683. -0. 5,960647E-05>' '<12,481627. 0. -6,286486E-05>'
 '<12,426662. 0. -6,258803E-05>' '<11,778013. 0. -5,9321046E-05>'
 '<11,72289. 0. -5,9043414E-05>' '<12,426769. 0. -6,2588566E-05>'
 '<-12,372129. -0. 6,231337E-05>' '<12,426773. 0. -6,258859E-05>'
 '<11,779644. 0. -5,932926E-05>' '<11,777897. 0. -5,932046E-05>'
 '<-12,372182. -0. 6,231363E-05>' '<11,779676. 0. -5,9329424E-05>'
 '<11,778033. 0. -5,9321148E-05>' '<-11,7799015. -0. 5,933056E-05>'
 '<11,779679. 0. -5,932944E-05>' '<-11,779748. -0. 5,9329785E-05>'
 '<11,777893. 0. -5,9320442E-05>' '<-11,779742. -0. 5,9329755E-05>'
 '<11,777838. 0. -5,9320162E-05>' '<11,777818. 0. -5,9320064E-05>'
 '<12,4267025. 0. -6,258823E-05>' '<11,777774. 0. -5,9319842E-05>'
 '<-12,426982. -0. 6,2589635E-05>' '<-12,42697. -0. 6,258958E-05>'
 '<11,777672. 0. -5,931933E-05>' '<-11,779716. -0. 5,932962E-05>'
 '<11,779589. 0. -5,9328984E-05>' '<11,778148. 0. -5,9321726E-05>'
 '<11,777796. 0. -5,931995E-05>' '<-11,779838. -0. 5,9330236E-05>'
 '<11,832908. 0. -5,959753E-05>' '<11,832917. 0. -5,9597576E-05>'
 '<11,778182. 0. -5,9321897E-05>' '<11,832951. 0. -5,9597744E-05>'
 '<-12,482132. -0. 6,286741E-05>' '<12,426671. 0. -6,258807E-05>'
 '<-12,427002. -0. 6,258974E-05>' '<11,779537. 0. -5,9328722E-05>'
 '<11,777758. 0. -5,9319762E-05>' '<-12,372027. -0. 6,231286E-05>'
 '<-11,724773. -0. 5,90529E-05>' '<11,77954. 0. -5,9328737E-05>'
 '<-11,72487. -0. 5,9053385E-05>' '<11,779474. 0. -5,9328406E-05>'
 '<-11,724721. -0. 5,9052636E-05>' '<11,777908. 0. -5,932052E-05>'
 '<11,777827. 0. -5,932011E-05>' '<11,777837. 0. -5,932016E-05>'
 '<11,777954. 0. -5,932075E-05>' '<11,7778845. 0. -5,93204E-05>'
 '<12,426575. 0. -6,2587584E-05>' '<12,4265785. 0. -6,2587605E-05>'
 '<-12,4271145. -0. 6,2590305E-05>' '<11,779574. 0. -5,932891E-05>'
 '<11,777797. 0. -5,931996E-05>' '<-11,7798605. -0. 5,9330352E-05>'
 '<11,777795. 0. -5,9319947E-05>' '<-11,779747. -0. 5,932978E-05>'
 '<11,77961. 0. -5,932909E-05>' '<-11,779898. -0. 5,9330538E-05>'
 '<11,77818. 0. -5,9321887E-05>' '<11,777829. 0. -5,9320122E-05>'
 '<11,777839. 0. -5,932017E-05>' '<12,426802. 0. -6,258873E-05>'
 '<11,777699. 0. -5,9319467E-05>' '<11,778043. 0. -5,9321195E-05>'
 '<12,426666. 0. -6,258805E-05>' '<-12,481978. -0. 6,286663E-05>'
 '<-12,481924. -0. 6,286636E-05>' '<11,779335. 0. -5,9327704E-05>'
 '<11,777828. 0. -5,9320115E-05>' '<-11,83467. -0. 5,9606406E-05>'
 '<11,779338. 0. -5,932772E-05>' '<-11,8346615. -0. 5,9606362E-05>'
 '<11,779386. 0. -5,932796E-05>' '<-11,779808. -0. 5,9330087E-05>'
 '<11,722755. 0. -5,9042737E-05>' '<11,722891. 0. -5,9043417E-05>'
 '<11,7779455. 0. -5,9320708E-05>' '<-12,37213. -0. 6,2313375E-05>'
 '<-12,37219. -0. 6,231367E-05>' '<11,779743. 0. -5,932976E-05>'
 '<-11,724929. -0. 5,9053684E-05>' '<11,779746. 0. -5,9329774E-05>'
 '<11,832947. 0. -5,9597725E-05>' '<-11,77982. -0. 5,933015E-05>'
 '<11,72446. 0. -5,905132E-05>' '<11,8328085. 0. -5,959703E-05>'
 '<-11,779667. -0. 5,9329377E-05>' '<11,832809. 0. -5,9597034E-05>'
 '<-11,779661. -0. 5,9329348E-05>' '<12,42651. 0. -6,258726E-05>'
 '<11,832753. 0. -5,959675E-05>' '<12,426444. 0. -6,258693E-05>'
 '<-12,426956. -0. 6,258951E-05>' '<-11,7797165. -0. 5,9329624E-05>'
 '<11,722754. 0. -5,9042726E-05>' '<-11,779814. -0. 5,9330116E-05>'
 '<11,779404. 0. -5,932805E-05>' '<-11,834809. -0. 5,9607108E-05>'
 '<11,777944. 0. -5,9320697E-05>' '<-11,834804. -0. 5,960708E-05>'
 '<12,481745. 0. -6,286546E-05>' '<12,481777. 0. -6,286562E-05>'
 '<11,777979. 0. -5,9320875E-05>' '<12,426871. 0. -6,258908E-05>'
 '<11,779605. 0. -5,9329064E-05>' '<-12,372028. -0. 6,231286E-05>'
 '<-11,724774. -0. 5,9052905E-05>' '<11,7797165. 0. -5,9329624E-05>'
 '<11,832743. 0. -5,9596696E-05>' '<-11,724727. -0. 5,9052665E-05>'
 '<11,832744. 0. -5,9596703E-05>' '<11,832798. 0. -5,9596976E-05>'
 '<12,426492. 0. -6,258717E-05>' '<11,722905. 0. -5,904349E-05>'
 '<11,832801. 0. -5,959699E-05>' '<-12,481952. -0. 6,28665E-05>'
 '<12,426496. 0. -6,258719E-05>' '<11,7794895. 0. -5,9328482E-05>'
 '<11,72288. 0. -5,9043366E-05>' '<-12,427097. -0. 6,259022E-05>'
 '<11,722879. 0. -5,904336E-05>' '<-11,779843. -0. 5,9330265E-05>'
 '<11,834485. 0. -5,9605474E-05>' '<11,722912. 0. -5,9043523E-05>'
 '<-11,779904. -0. 5,9330574E-05>' '<11,722913. 0. -5,904353E-05>'
 '<-11,779899. -0. 5,9330545E-05>' '<12,426656. 0. -6,2588E-05>'
 '<11,777766. 0. -5,9319802E-05>' '<-12,427011. -0. 6,258978E-05>'
 '<12,42666. 0. -6,258801E-05>' '<-12,426955. -0. 6,2589505E-05>'
 '<11,724419. 0. -5,905111E-05>' '<-11,779701. -0. 5,9329548E-05>'
 '<11,72443. 0. -5,905117E-05>' '<-11,779714. -0. 5,9329614E-05>'
 '<11,724469. 0. -5,9051366E-05>' '<-11,779708. -0. 5,9329584E-05>'
 '<11,722903. 0. -5,904348E-05>' '<11,777817. 0. -5,9320057E-05>'
 '<12,426836. 0. -6,25889E-05>' '<11,777942. 0. -5,9320686E-05>'
 '<-12,427105. -0. 6,259026E-05>' '<12,42684. 0. -6,258892E-05>'
 '<11,777862. 0. -5,9320282E-05>' '<12,426694. 0. -6,258819E-05>'
 '<11,777895. 0. -5,9320453E-05>' '<-12,427059. -0. 6,259003E-05>'
 '<11,779659. 0. -5,9329337E-05>' '<11,777896. 0. -5,9320457E-05>'
 '<11,777894. 0. -5,9320446E-05>' '<11,779661. 0. -5,9329348E-05>'
 '<11,777728. 0. -5,9319613E-05>' '<-11,77965. -0. 5,932929E-05>'
 '<11,779522. 0. -5,9328646E-05>' '<-11,779644. -0. 5,932926E-05>'
 '<11,777956. 0. -5,932076E-05>' '<-11,779737. -0. 5,9329734E-05>'
 '<11,832957. 0. -5,959778E-05>' '<11,722783. 0. -5,9042875E-05>'
 '<12,426598. 0. -6,25877E-05>' '<11,832893. 0. -5,9597456E-05>'
 '<-12,371989. -0. 6,231266E-05>' '<12,426601. 0. -6,258772E-05>'
 '<12,42661. 0. -6,2587766E-05>' '<11,832789. 0. -5,9596932E-05>'
 '<11,779512. 0. -5,93286E-05>' '<11,832791. 0. -5,9596943E-05>'
 '<11,779514. 0. -5,932861E-05>' '<11,832808. 0. -5,9597023E-05>'
 '<11,779639. 0. -5,932924E-05>' '<-11,779836. -0. 5,933023E-05>'
 '<11,723028. 0. -5,904411E-05>' '<12,426733. 0. -6,2588384E-05>'
 '<11,7230625. 0. -5,9044283E-05>' '<-12,427166. -0. 6,259057E-05>'
 '<-12,427004. -0. 6,258975E-05>' '<11,777864. 0. -5,9320297E-05>'
 '<-11,779703. -0. 5,932956E-05>' '<11,779542. 0. -5,9328748E-05>'
 '<-11,779597. -0. 5,9329024E-05>' '<11,77789. 0. -5,9320428E-05>'
 '<12,426507. 0. -6,258725E-05>' '<11,77794. 0. -5,932068E-05>'
 '<11,777748. 0. -5,931971E-05>' '<12,426514. 0. -6,258728E-05>'
 '<-12,427202. -0. 6,259075E-05>' '<11,779508. 0. -5,9328573E-05>'
 '<11,7795105. 0. -5,9328588E-05>' '<11,777786. 0. -5,9319904E-05>'
 '<-11,780003. -0. 5,933107E-05>' '<11,834655. 0. -5,960633E-05>'
 '<11,833089. 0. -5,9598442E-05>' '<11,8329525. 0. -5,9597754E-05>'
 '<12,426728. 0. -6,258836E-05>' '<-12,426912. -0. 6,2589286E-05>'
 '<11,778001. 0. -5,9320984E-05>' '<-12,426866. -0. 6,258905E-05>'
 '<11,724422. 0. -5,9051134E-05>' '<-11,834687. -0. 5,9606493E-05>'
 '<11,777873. 0. -5,932034E-05>' '<-11,834684. -0. 5,960648E-05>'
 '<11,723031. 0. -5,9044123E-05>' '<12,481751. 0. -6,286549E-05>'
 '<11,777927. 0. -5,9320617E-05>' '<12,481752. 0. -6,2865496E-05>'
 '<12,481756. 0. -6,286551E-05>' '<11,83466. 0. -5,960635E-05>'
 '<11,777811. 0. -5,9320028E-05>' '<11,779405. 0. -5,9328057E-05>'
 '<11,777773. 0. -5,931984E-05>' '<11,777769. 0. -5,9319817E-05>'
 '<11,832887. 0. -5,9597423E-05>' '<12,426663. 0. -6,2588035E-05>'
 '<11,832735. 0. -5,959666E-05>' '<11,832745. 0. -5,9596707E-05>'
 '<12,426714. 0. -6,258829E-05>' '<11,832783. 0. -5,95969E-05>'
 '<-12,426869. -0. 6,258907E-05>' '<11,832784. 0. -5,9596903E-05>'
 '<11,723029. 0. -5,9044116E-05>' '<11,778041. 0. -5,9321188E-05>'
 '<12,481785. 0. -6,2865656E-05>' '<11,723063. 0. -5,9044287E-05>'
 '<12,481789. 0. -6,286568E-05>' '<-12,427109. -0. 6,2590276E-05>'
 '<12,48165. 0. -6,286498E-05>' '<11,722773. 0. -5,9042824E-05>'
 '<11,834521. 0. -5,9605656E-05>' '<11,834458. 0. -5,960534E-05>'
 '<11,832891. 0. -5,9597445E-05>' '<11,777606. 0. -5,9318998E-05>'
 '<11,777953. 0. -5,9320744E-05>' '<11,8328. 0. -5,9596987E-05>'
 '<12,371592. 0. -6,231066E-05>' '<11,777958. 0. -5,932077E-05>'
 '<12,371721. 0. -6,2311316E-05>' '<11,7779255. 0. -5,9320606E-05>'
 '<-11,834817. -0. 5,9607144E-05>' '<-11,834877. -0. 5,9607446E-05>'
 '<11,779611. 0. -5,9329093E-05>' '<11,778045. 0. -5,9321206E-05>'
 '<11,777907. 0. -5,9320515E-05>' '<11,722782. 0. -5,904287E-05>'
 '<-12,372036. -0. 6,2312894E-05>' '<-12,372131. -0. 6,2313375E-05>'
 '<12,4266. 0. -6,2587715E-05>' '<11,779519. 0. -5,932863E-05>'
 '<11,777955. 0. -5,9320755E-05>' '<11,83279. 0. -5,9596936E-05>'
 '<-11,724733. -0. 5,9052698E-05>' '<11,777778. 0. -5,931986E-05>'
 '<11,833065. 0. -5,9598322E-05>' '<11,777787. 0. -5,9319907E-05>'
 '<-12,427023. -0. 6,258985E-05>' '<-12,426909. -0. 6,258927E-05>'
 '<12,371754. 0. -6,2311476E-05>' '<11,7779665. 0. -5,9320813E-05>'
 '<-11,834878. -0. 5,9607453E-05>' '<11,724461. 0. -5,9051326E-05>'
 '<11,724487. 0. -5,905146E-05>' '<11,7779045. 0. -5,93205E-05>'
 '<11,777753. 0. -5,9319736E-05>' '<12,48158. 0. -6,286462E-05>'
 '<11,777762. 0. -5,9319784E-05>' '<-12,426958. -0. 6,258952E-05>'
 '<-12,37198. -0. 6,231262E-05>' '<12,426648. 0. -6,2587955E-05>'
 '<11,777738. 0. -5,931966E-05>' '<-12,372001. -0. 6,231272E-05>'
 '<11,77774. 0. -5,9319667E-05>']
PR_118.Y.CurrentForce
['<-0. 0. 0>' '<-6,2191155E-08. 106,84366. 8,3349007E-13>'
 '<-6,217929E-08. 106,823265. 8,3333096E-13>'
 '<-6,217901E-08. 106,82279. 8,333273E-13>'
 '<-4,074534E-07. 700. 5,460718E-12>'
 '<-1,3899798E-07. 238,79684. 1,8628601E-12>'
 '<-6,2276406E-08. 106,99011. 8,3463255E-13>'
 '<-6,249141E-08. 107,35949. 8,375141E-13>'
 '<-6,2863876E-08. 107,999374. 8,4250586E-13>'
 '<-6,318367E-08. 108,54878. 8,4679177E-13>'
 '<-6,251125E-08. 107,39356. 8,377799E-13>'
 '<-7,82348E-08. 134,40643. 1,048508E-12>'
 '<-6,3679686E-08. 109,40093. 8,5343944E-13>'
 '<-6,249558E-08. 107,36665. 8,3757E-13>'
 '<-6,284822E-08. 107,97249. 8,422961E-13>'
 '<-6,316779E-08. 108,5215. 8,4657894E-13>'
 '<-6,284695E-08. 107,97031. 8,422791E-13>'
 '<-6,252741E-08. 107,42133. 8,3799656E-13>'
 '<-6,2815126E-08. 107,91563. 8,418525E-13>'
 '<-6,252738E-08. 107,42127. 8,3799607E-13>'
 '<-6,319976E-08. 108,576416. 8,4700736E-13>'
 '<-6,280192E-08. 107,89294. 8,416755E-13>'
 '<-6,2495516E-08. 107,36654. 8,3756905E-13>'
 '<-6,321298E-08. 108,59914. 8,4718463E-13>'
 '<-6,289292E-08. 108,049286. 8,428952E-13>'
 '<-6,321299E-08. 108,59915. 8,4718474E-13>'
 '<-6,287942E-08. 108,026085. 8,427142E-13>'
 '<-6,31995E-08. 108,57597. 8,470039E-13>'
 '<-6,2495154E-08. 107,36592. 8,3756423E-13>'
 '<-6,289264E-08. 108,0488. 8,428914E-13>'
 '<-6,2879415E-08. 108,02607. 8,427141E-13>'
 '<-6,316754E-08. 108,52107. 8,4657563E-13>'
 '<-6,2847356E-08. 107,971. 8,422845E-13>'
 '<-6,284766E-08. 107,97152. 8,4228853E-13>'
 '<-6,31676E-08. 108,52117. 8,465764E-13>'
 '<-6,287952E-08. 108,02625. 8,4271555E-13>'
 '<-6,2847135E-08. 107,97062. 8,4228154E-13>'
 '<-6,287938E-08. 108,02601. 8,427136E-13>'
 '<-6,316762E-08. 108,52121. 8,465767E-13>'
 '<-6,281527E-08. 107,91587. 8,418544E-13>'
 '<-6,2495204E-08. 107,366005. 8,3756493E-13>'
 '<-6,287984E-08. 108,02681. 8,427199E-13>'
 '<-6,284672E-08. 107,96991. 8,42276E-13>'
 '<-6,2495324E-08. 107,36621. 8,375665E-13>'
 '<-6,2847064E-08. 107,9705. 8,4228056E-13>'
 '<-6,249545E-08. 107,36643. 8,3756824E-13>'
 '<-6,252731E-08. 107,42117. 8,3799525E-13>'
 '<-6,284812E-08. 107,97231. 8,422947E-13>'
 '<-6,319975E-08. 108,57641. 8,470073E-13>'
 '<-6,249551E-08. 107,36652. 8,3756895E-13>'
 '<-6,288009E-08. 108,02724. 8,427232E-13>'
 '<-6,248229E-08. 107,34383. 8,373919E-13>'

In [2]:
import pandas as pd
faults = pd.read_parquet("../data/training/0_0pct_faults_rep_1/faults.parquet")
measurements = pd.read_parquet("../data/training/0_0pct_faults_rep_1/measurements.parquet")
parameters = pd.read_parquet("../data/training/0_0pct_faults_rep_1/parameters.parquet")

In [5]:
list(parameters.columns)

['AMP_1.Acceleration',
 'AMP_1.Deceleration',
 'AMP_1.Length',
 'AMP_1.MaximumTorque',
 'AMP_1.PE1',
 'AMP_1.Resistance',
 'AMP_1.RollerDamping',
 'AMP_1.TargetSpeed',
 'AMP_1.Width',
 'AMP_2.Acceleration',
 'AMP_2.Deceleration',
 'AMP_2.Length',
 'AMP_2.MaximumTorque',
 'AMP_2.PE1',
 'AMP_2.Resistance',
 'AMP_2.RollerDamping',
 'AMP_2.TargetSpeed',
 'AMP_2.Width',
 'AMP_3.Acceleration',
 'AMP_3.Deceleration',
 'AMP_3.Length',
 'AMP_3.MaximumTorque',
 'AMP_3.PE1',
 'AMP_3.Resistance',
 'AMP_3.RollerDamping',
 'AMP_3.TargetSpeed',
 'AMP_3.Width',
 'AMR_1.Acceleration',
 'AMR_1.TargetSpeed',
 'AMR_1.WorldY',
 'AMR_2.Acceleration',
 'AMR_2.TargetSpeed',
 'AMR_2.WorldY',
 'AMR_3.Acceleration',
 'AMR_3.TargetSpeed',
 'AMR_3.WorldY',
 'CC_1.Acceleration',
 'CC_1.CurrentDirection',
 'CC_1.Deceleration',
 'CC_1.Height',
 'CC_1.Length',
 'CC_1.MaximumTorque',
 'CC_1.PE1',
 'CC_1.Resistance',
 'CC_1.RollerDamping',
 'CC_1.TargetSpeed',
 'CC_1.Width',
 'CC_147.Acceleration',
 'CC_147.CurrentDirection',
 'CC_147.Deceleration',
 'CC_147.Height',
 'CC_147.Length',
 'CC_147.MaximumTorque',
 'CC_147.PE1',
 'CC_147.Resistance',
 'CC_147.RollerDamping',
 'CC_147.TargetSpeed',
 'CC_147.Width',
 'CC_148.Acceleration',
 'CC_148.CurrentDirection',
 'CC_148.Deceleration',
 'CC_148.Height',
 'CC_148.Length',
 'CC_148.MaximumTorque',
 'CC_148.PE1',
 'CC_148.Resistance',
 'CC_148.RollerDamping',
 'CC_148.TargetSpeed',
 'CC_148.Width',
 'CC_149.Acceleration',
 'CC_149.CurrentDirection',
 'CC_149.Deceleration',
 'CC_149.Height',
 'CC_149.Length',
 'CC_149.MaximumTorque',
 'CC_149.PE1',
 'CC_149.Resistance',
 'CC_149.RollerDamping',
 'CC_149.TargetSpeed',
 'CC_149.Width',
 'CC_150.Acceleration',
 'CC_150.CurrentDirection',
 'CC_150.Deceleration',
 'CC_150.Height',
 'CC_150.Length',
 'CC_150.MaximumTorque',
 'CC_150.PE1',
 'CC_150.Resistance',
 'CC_150.RollerDamping',
 'CC_150.TargetSpeed',
 'CC_150.Width',
 'CC_151.Acceleration',
 'CC_151.CurrentDirection',
 'CC_151.Deceleration',
 'CC_151.Height',
 'CC_151.Length',
 'CC_151.MaximumTorque',
 'CC_151.PE1',
 'CC_151.Resistance',
 'CC_151.RollerDamping',
 'CC_151.TargetSpeed',
 'CC_151.Width',
 'CC_152.Acceleration',
 'CC_152.CurrentDirection',
 'CC_152.Deceleration',
 'CC_152.Height',
 'CC_152.Length',
 'CC_152.MaximumTorque',
 'CC_152.PE1',
 'CC_152.Resistance',
 'CC_152.RollerDamping',
 'CC_152.TargetSpeed',
 'CC_152.Width',
 'CC_153.Acceleration',
 'CC_153.CurrentDirection',
 'CC_153.Deceleration',
 'CC_153.Height',
 'CC_153.Length',
 'CC_153.MaximumTorque',
 'CC_153.PE1',
 'CC_153.Resistance',
 'CC_153.RollerDamping',
 'CC_153.TargetSpeed',
 'CC_153.Width',
 'CC_154.Acceleration',
 'CC_154.CurrentDirection',
 'CC_154.Deceleration',
 'CC_154.Height',
 'CC_154.Length',
 'CC_154.MaximumTorque',
 'CC_154.PE1',
 'CC_154.Resistance',
 'CC_154.RollerDamping',
 'CC_154.TargetSpeed',
 'CC_154.Width',
 'CC_155.Acceleration',
 'CC_155.CurrentDirection',
 'CC_155.Deceleration',
 'CC_155.Height',
 'CC_155.Length',
 'CC_155.MaximumTorque',
 'CC_155.PE1',
 'CC_155.Resistance',
 'CC_155.RollerDamping',
 'CC_155.TargetSpeed',
 'CC_155.Width',
 'CC_156.Acceleration',
 'CC_156.CurrentDirection',
 'CC_156.Deceleration',
 'CC_156.Height',
 'CC_156.Length',
 'CC_156.MaximumTorque',
 'CC_156.PE1',
 'CC_156.Resistance',
 'CC_156.RollerDamping',
 'CC_156.TargetSpeed',
 'CC_156.Width',
 'CC_157.Acceleration',
 'CC_157.CurrentDirection',
 'CC_157.Deceleration',
 'CC_157.Height',
 'CC_157.Length',
 'CC_157.MaximumTorque',
 'CC_157.PE1',
 'CC_157.Resistance',
 'CC_157.RollerDamping',
 'CC_157.TargetSpeed',
 'CC_157.Width',
 'CC_158.Acceleration',
 'CC_158.CurrentDirection',
 'CC_158.Deceleration',
 'CC_158.Height',
 'CC_158.Length',
 'CC_158.MaximumTorque',
 'CC_158.PE1',
 'CC_158.Resistance',
 'CC_158.RollerDamping',
 'CC_158.TargetSpeed',
 'CC_158.Width',
 'CC_16.Acceleration',
 'CC_16.CurrentDirection',
 'CC_16.Deceleration',
 'CC_16.Height',
 'CC_16.Length',
 'CC_16.MaximumTorque',
 'CC_16.PE1',
 'CC_16.Resistance',
 'CC_16.RollerDamping',
 'CC_16.TargetSpeed',
 'CC_16.Width',
 'CC_17.Acceleration',
 'CC_17.CurrentDirection',
 'CC_17.Deceleration',
 'CC_17.Height',
 'CC_17.Length',
 'CC_17.MaximumTorque',
 'CC_17.PE1',
 'CC_17.Resistance',
 'CC_17.RollerDamping',
 'CC_17.TargetSpeed',
 'CC_17.Width',
 'CC_18.Acceleration',
 'CC_18.CurrentDirection',
 'CC_18.Deceleration',
 'CC_18.Height',
 'CC_18.Length',
 'CC_18.MaximumTorque',
 'CC_18.PE1',
 'CC_18.Resistance',
 'CC_18.RollerDamping',
 'CC_18.TargetSpeed',
 'CC_18.Width',
 'CC_19.Acceleration',
 'CC_19.CurrentDirection',
 'CC_19.Deceleration',
 'CC_19.Height',
 'CC_19.Length',
 'CC_19.MaximumTorque',
 'CC_19.PE1',
 'CC_19.Resistance',
 'CC_19.RollerDamping',
 'CC_19.TargetSpeed',
 'CC_19.Width',
 'CC_2.Acceleration',
 'CC_2.CurrentDirection',
 'CC_2.Deceleration',
 'CC_2.Height',
 'CC_2.Length',
 'CC_2.MaximumTorque',
 'CC_2.PE1',
 'CC_2.Resistance',
 'CC_2.RollerDamping',
 'CC_2.TargetSpeed',
 'CC_2.Width',
 'CC_20.Acceleration',
 'CC_20.CurrentDirection',
 'CC_20.Deceleration',
 'CC_20.Height',
 'CC_20.Length',
 'CC_20.MaximumTorque',
 'CC_20.PE1',
 'CC_20.Resistance',
 'CC_20.RollerDamping',
 'CC_20.TargetSpeed',
 'CC_20.Width',
 'CC_3.Acceleration',
 'CC_3.CurrentDirection',
 'CC_3.Deceleration',
 'CC_3.Height',
 'CC_3.Length',
 'CC_3.MaximumTorque',
 'CC_3.PE1',
 'CC_3.Resistance',
 'CC_3.RollerDamping',
 'CC_3.TargetSpeed',
 'CC_3.Width',
 'CC_4.Acceleration',
 'CC_4.CurrentDirection',
 'CC_4.Deceleration',
 'CC_4.Height',
 'CC_4.Length',
 'CC_4.MaximumTorque',
 'CC_4.PE1',
 'CC_4.Resistance',
 'CC_4.RollerDamping',
 'CC_4.TargetSpeed',
 'CC_4.Width',
 'CC_5.Acceleration',
 'CC_5.CurrentDirection',
 'CC_5.Deceleration',
 'CC_5.Height',
 'CC_5.Length',
 'CC_5.MaximumTorque',
 'CC_5.PE1',
 'CC_5.Resistance',
 'CC_5.RollerDamping',
 'CC_5.TargetSpeed',
 'CC_5.Width',
 'CC_6.Acceleration',
 'CC_6.CurrentDirection',
 'CC_6.Deceleration',
 'CC_6.Height',
 'CC_6.Length',
 'CC_6.MaximumTorque',
 'CC_6.PE1',
 'CC_6.Resistance',
 'CC_6.RollerDamping',
 'CC_6.TargetSpeed',
 'CC_6.Width',
 'CC_LP.Acceleration',
 'CC_LP.CurrentDirection',
 'CC_LP.Deceleration',
 'CC_LP.Height',
 'CC_LP.Length',
 'CC_LP.MaximumTorque',
 'CC_LP.PE1',
 'CC_LP.Resistance',
 'CC_LP.RollerDamping',
 'CC_LP.TargetSpeed',
 'CC_LP.Width',
 'CLT_108.Acceleration',
 'CLT_108.CurrentDirection',
 'CLT_108.Deceleration',
 'CLT_108.Height',
 'CLT_108.Length',
 'CLT_108.MaximumTorque',
 'CLT_108.PE1',
 'CLT_108.PE2',
 'CLT_108.PE3',
 'CLT_108.PE4',
 'CLT_108.Resistance',
 'CLT_108.RollerDamping',
 'CLT_108.TargetSpeed',
 'CLT_108.Width',
 'CLT_125.Acceleration',
 'CLT_125.CurrentDirection',
 'CLT_125.Deceleration',
 'CLT_125.Height',
 'CLT_125.Length',
 'CLT_125.MaximumTorque',
 'CLT_125.PE1',
 'CLT_125.PE2',
 'CLT_125.PE3',
 'CLT_125.PE4',
 'CLT_125.Resistance',
 'CLT_125.RollerDamping',
 'CLT_125.TargetSpeed',
 'CLT_125.Width',
 'CLT_137.Acceleration',
 'CLT_137.CurrentDirection',
 'CLT_137.Deceleration',
 'CLT_137.Height',
 'CLT_137.Length',
 'CLT_137.MaximumTorque',
 'CLT_137.PE1',
 'CLT_137.PE2',
 'CLT_137.PE3',
 'CLT_137.PE4',
 'CLT_137.Resistance',
 'CLT_137.RollerDamping',
 'CLT_137.TargetSpeed',
 'CLT_137.Width',
 'CLT_15.Acceleration',
 'CLT_15.CurrentDirection',
 'CLT_15.Deceleration',
 'CLT_15.Height',
 'CLT_15.Length',
 'CLT_15.MaximumTorque',
 'CLT_15.PE1',
 'CLT_15.PE2',
 'CLT_15.PE3',
 'CLT_15.PE4',
 'CLT_15.Resistance',
 'CLT_15.RollerDamping',
 'CLT_15.TargetSpeed',
 'CLT_15.Width',
 'CLT_28.Acceleration',
 'CLT_28.CurrentDirection',
 'CLT_28.Deceleration',
 'CLT_28.Height',
 'CLT_28.Length',
 'CLT_28.MaximumTorque',
 'CLT_28.PE1',
 'CLT_28.PE2',
 'CLT_28.PE3',
 'CLT_28.PE4',
 'CLT_28.Resistance',
 'CLT_28.RollerDamping',
 'CLT_28.TargetSpeed',
 'CLT_28.Width',
 'CLT_40.Acceleration',
 'CLT_40.CurrentDirection',
 'CLT_40.Deceleration',
 'CLT_40.Height',
 'CLT_40.Length',
 'CLT_40.MaximumTorque',
 'CLT_40.PE1',
 'CLT_40.PE2',
 'CLT_40.PE3',
 'CLT_40.PE4',
 'CLT_40.Resistance',
 'CLT_40.RollerDamping',
 'CLT_40.TargetSpeed',
 'CLT_40.Width',
 'CLT_47.Acceleration',
 'CLT_47.CurrentDirection',
 'CLT_47.Deceleration',
 'CLT_47.Height',
 'CLT_47.Length',
 'CLT_47.MaximumTorque',
 'CLT_47.PE1',
 'CLT_47.PE2',
 'CLT_47.PE3',
 'CLT_47.PE4',
 'CLT_47.Resistance',
 'CLT_47.RollerDamping',
 'CLT_47.TargetSpeed',
 'CLT_47.Width',
 'CLT_59.Acceleration',
 'CLT_59.CurrentDirection',
 'CLT_59.Deceleration',
 'CLT_59.Height',
 'CLT_59.Length',
 'CLT_59.MaximumTorque',
 'CLT_59.PE1',
 'CLT_59.PE2',
 'CLT_59.PE3',
 'CLT_59.PE4',
 'CLT_59.Resistance',
 'CLT_59.RollerDamping',
 'CLT_59.TargetSpeed',
 'CLT_59.Width',
 'CLT_89.Acceleration',
 'CLT_89.CurrentDirection',
 'CLT_89.Deceleration',
 'CLT_89.Height',
 'CLT_89.Length',
 'CLT_89.MaximumTorque',
 'CLT_89.PE1',
 'CLT_89.PE2',
 'CLT_89.PE3',
 'CLT_89.PE4',
 'CLT_89.Resistance',
 'CLT_89.RollerDamping',
 'CLT_89.TargetSpeed',
 'CLT_89.Width',
 'CLT_96.Acceleration',
 'CLT_96.CurrentDirection',
 'CLT_96.Deceleration',
 'CLT_96.Height',
 'CLT_96.Length',
 'CLT_96.MaximumTorque',
 'CLT_96.PE1',
 'CLT_96.PE2',
 'CLT_96.PE3',
 'CLT_96.PE4',
 'CLT_96.Resistance',
 'CLT_96.RollerDamping',
 'CLT_96.TargetSpeed',
 'CLT_96.Width',
 'Lift.Acceleration',
 'Lift.Deceleration',
 'Lift.Length',
 'Lift.MaximumTorque',
 'Lift.Resistance',
 'Lift.RollerDamping',
 'Lift.TargetSpeed',
 'Lift.Width',
 'PR_118.X.Mass',
 'PR_118.X.MaximumForce',
 'PR_118.X.Resistance',
 'PR_118.X.TargetSpeed',
 'PR_118.Y.Mass',
 'PR_118.Y.MaximumForce',
 'PR_118.Y.Resistance',
 'PR_118.Y.TargetSpeed',
 'PR_118.Z.Mass',
 'PR_118.Z.MaximumForce',
 'PR_118.Z.Resistance',
 'PR_118.Z.TargetSpeed',
 'PR_7.X.Mass',
 'PR_7.X.MaximumForce',
 'PR_7.X.Resistance',
 'PR_7.X.TargetSpeed',
 'PR_7.Y.Mass',
 'PR_7.Y.MaximumForce',
 'PR_7.Y.Resistance',
 'PR_7.Y.TargetSpeed',
 'PR_7.Z.Mass',
 'PR_7.Z.MaximumForce',
 'PR_7.Z.Resistance',
 'PR_7.Z.TargetSpeed',
 'RB_1.Axis1.Acceleration',
 'RB_1.Axis1.Deceleration',
 'RB_1.Axis1.PositionLowerLimit',
 'RB_1.Axis1.PositionUpperLimit',
 'RB_1.Axis1.TargetSpeed',
 'RB_1.Axis2.Acceleration',
 'RB_1.Axis2.Deceleration',
 'RB_1.Axis2.PositionLowerLimit',
 'RB_1.Axis2.PositionUpperLimit',
 'RB_1.Axis2.TargetSpeed',
 'RB_1.Axis3.Acceleration',
 'RB_1.Axis3.Deceleration',
 'RB_1.Axis3.PositionLowerLimit',
 'RB_1.Axis3.PositionUpperLimit',
 'RB_1.Axis3.TargetSpeed',
 'RB_1.Axis4.Acceleration',
 'RB_1.Axis4.Deceleration',
 'RB_1.Axis4.PositionLowerLimit',
 'RB_1.Axis4.PositionUpperLimit',
 'RB_1.Axis4.TargetSpeed',
 'RB_1.Axis5.Acceleration',
 'RB_1.Axis5.Deceleration',
 'RB_1.Axis5.PositionLowerLimit',
 'RB_1.Axis5.PositionUpperLimit',
 'RB_1.Axis5.TargetSpeed',
 'RB_1.Axis6.Acceleration',
 'RB_1.Axis6.Deceleration',
 'RB_1.Axis6.PositionLowerLimit',
 'RB_1.Axis6.PositionUpperLimit',
 'RB_1.Axis6.TargetSpeed',
 'RB_1.ProcessTime',
 'RB_11.Axis1.Acceleration',
 'RB_11.Axis1.Deceleration',
 'RB_11.Axis1.PositionLowerLimit',
 'RB_11.Axis1.PositionUpperLimit',
 'RB_11.Axis1.TargetSpeed',
 'RB_11.Axis2.Acceleration',
 'RB_11.Axis2.Deceleration',
 'RB_11.Axis2.PositionLowerLimit',
 'RB_11.Axis2.PositionUpperLimit',
 'RB_11.Axis2.TargetSpeed',
 'RB_11.Axis3.Acceleration',
 'RB_11.Axis3.Deceleration',
 'RB_11.Axis3.PositionLowerLimit',
 'RB_11.Axis3.PositionUpperLimit',
 'RB_11.Axis3.TargetSpeed',
 'RB_11.Axis4.Acceleration',
 'RB_11.Axis4.Deceleration',
 'RB_11.Axis4.PositionLowerLimit',
 'RB_11.Axis4.PositionUpperLimit',
 'RB_11.Axis4.TargetSpeed',
 'RB_11.Axis5.Acceleration',
 'RB_11.Axis5.Deceleration',
 'RB_11.Axis5.PositionLowerLimit',
 'RB_11.Axis5.PositionUpperLimit',
 'RB_11.Axis5.TargetSpeed',
 'RB_11.Axis6.Acceleration',
 'RB_11.Axis6.Deceleration',
 'RB_11.Axis6.PositionLowerLimit',
 'RB_11.Axis6.PositionUpperLimit',
 'RB_11.Axis6.TargetSpeed',
 'RB_11.ProcessTime',
 'RB_12.Axis1.Acceleration',
 'RB_12.Axis1.Deceleration',
 'RB_12.Axis1.PositionLowerLimit',
 'RB_12.Axis1.PositionUpperLimit',
 'RB_12.Axis1.TargetSpeed',
 'RB_12.Axis2.Acceleration',
 'RB_12.Axis2.Deceleration',
 'RB_12.Axis2.PositionLowerLimit',
 'RB_12.Axis2.PositionUpperLimit',
 'RB_12.Axis2.TargetSpeed',
 'RB_12.Axis3.Acceleration',
 'RB_12.Axis3.Deceleration',
 'RB_12.Axis3.PositionLowerLimit',
 'RB_12.Axis3.PositionUpperLimit',
 'RB_12.Axis3.TargetSpeed',
 'RB_12.Axis4.Acceleration',
 'RB_12.Axis4.Deceleration',
 'RB_12.Axis4.PositionLowerLimit',
 'RB_12.Axis4.PositionUpperLimit',
 'RB_12.Axis4.TargetSpeed',
 'RB_12.Axis5.Acceleration',
 'RB_12.Axis5.Deceleration',
 'RB_12.Axis5.PositionLowerLimit',
 'RB_12.Axis5.PositionUpperLimit',
 'RB_12.Axis5.TargetSpeed',
 'RB_12.Axis6.Acceleration',
 'RB_12.Axis6.Deceleration',
 'RB_12.Axis6.PositionLowerLimit',
 'RB_12.Axis6.PositionUpperLimit',
 'RB_12.Axis6.TargetSpeed',
 'RB_12.ProcessTime',
 'RB_2.Axis1.Acceleration',
 'RB_2.Axis1.Deceleration',
 'RB_2.Axis1.PositionLowerLimit',
 'RB_2.Axis1.PositionUpperLimit',
 'RB_2.Axis1.TargetSpeed',
 'RB_2.Axis2.Acceleration',
 'RB_2.Axis2.Deceleration',
 'RB_2.Axis2.PositionLowerLimit',
 'RB_2.Axis2.PositionUpperLimit',
 'RB_2.Axis2.TargetSpeed',
 'RB_2.Axis3.Acceleration',
 'RB_2.Axis3.Deceleration',
 'RB_2.Axis3.PositionLowerLimit',
 'RB_2.Axis3.PositionUpperLimit',
 'RB_2.Axis3.TargetSpeed',
 'RB_2.Axis4.Acceleration',
 'RB_2.Axis4.Deceleration',
 'RB_2.Axis4.PositionLowerLimit',
 'RB_2.Axis4.PositionUpperLimit',
 'RB_2.Axis4.TargetSpeed',
 'RB_2.Axis5.Acceleration',
 'RB_2.Axis5.Deceleration',
 'RB_2.Axis5.PositionLowerLimit',
 'RB_2.Axis5.PositionUpperLimit',
 'RB_2.Axis5.TargetSpeed',
 'RB_2.Axis6.Acceleration',
 'RB_2.Axis6.Deceleration',
 'RB_2.Axis6.PositionLowerLimit',
 'RB_2.Axis6.PositionUpperLimit',
 'RB_2.Axis6.TargetSpeed',
 'RB_2.ProcessTime',
 'RB_21.Axis1.Acceleration',
 'RB_21.Axis1.Deceleration',
 'RB_21.Axis1.PositionLowerLimit',
 'RB_21.Axis1.PositionUpperLimit',
 'RB_21.Axis1.TargetSpeed',
 'RB_21.Axis2.Acceleration',
 'RB_21.Axis2.Deceleration',
 'RB_21.Axis2.PositionLowerLimit',
 'RB_21.Axis2.PositionUpperLimit',
 'RB_21.Axis2.TargetSpeed',
 'RB_21.Axis3.Acceleration',
 'RB_21.Axis3.Deceleration',
 'RB_21.Axis3.PositionLowerLimit',
 'RB_21.Axis3.PositionUpperLimit',
 'RB_21.Axis3.TargetSpeed',
 'RB_21.Axis4.Acceleration',
 'RB_21.Axis4.Deceleration',
 'RB_21.Axis4.PositionLowerLimit',
 'RB_21.Axis4.PositionUpperLimit',
 'RB_21.Axis4.TargetSpeed',
 'RB_21.Axis5.Acceleration',
 'RB_21.Axis5.Deceleration',
 'RB_21.Axis5.PositionLowerLimit',
 'RB_21.Axis5.PositionUpperLimit',
 'RB_21.Axis5.TargetSpeed',
 'RB_21.Axis6.Acceleration',
 'RB_21.Axis6.Deceleration',
 'RB_21.Axis6.PositionLowerLimit',
 'RB_21.Axis6.PositionUpperLimit',
 'RB_21.Axis6.TargetSpeed',
 'RB_21.ProcessTime',
 'RB_22.Axis1.Acceleration',
 'RB_22.Axis1.Deceleration',
 'RB_22.Axis1.PositionLowerLimit',
 'RB_22.Axis1.PositionUpperLimit',
 'RB_22.Axis1.TargetSpeed',
 'RB_22.Axis2.Acceleration',
 'RB_22.Axis2.Deceleration',
 'RB_22.Axis2.PositionLowerLimit',
 'RB_22.Axis2.PositionUpperLimit',
 'RB_22.Axis2.TargetSpeed',
 'RB_22.Axis3.Acceleration',
 'RB_22.Axis3.Deceleration',
 'RB_22.Axis3.PositionLowerLimit',
 'RB_22.Axis3.PositionUpperLimit',
 'RB_22.Axis3.TargetSpeed',
 'RB_22.Axis4.Acceleration',
 'RB_22.Axis4.Deceleration',
 'RB_22.Axis4.PositionLowerLimit',
 'RB_22.Axis4.PositionUpperLimit',
 'RB_22.Axis4.TargetSpeed',
 'RB_22.Axis5.Acceleration',
 'RB_22.Axis5.Deceleration',
 'RB_22.Axis5.PositionLowerLimit',
 'RB_22.Axis5.PositionUpperLimit',
 'RB_22.Axis5.TargetSpeed',
 'RB_22.Axis6.Acceleration',
 'RB_22.Axis6.Deceleration',
 'RB_22.Axis6.PositionLowerLimit',
 'RB_22.Axis6.PositionUpperLimit',
 'RB_22.Axis6.TargetSpeed',
 'RB_22.ProcessTime',
 'RB_3.Axis1.Acceleration',
 'RB_3.Axis1.Deceleration',
 'RB_3.Axis1.PositionLowerLimit',
 'RB_3.Axis1.PositionUpperLimit',
 'RB_3.Axis1.TargetSpeed',
 'RB_3.Axis2.Acceleration',
 'RB_3.Axis2.Deceleration',
 'RB_3.Axis2.PositionLowerLimit',
 'RB_3.Axis2.PositionUpperLimit',
 'RB_3.Axis2.TargetSpeed',
 'RB_3.Axis3.Acceleration',
 'RB_3.Axis3.Deceleration',
 'RB_3.Axis3.PositionLowerLimit',
 'RB_3.Axis3.PositionUpperLimit',
 'RB_3.Axis3.TargetSpeed',
 'RB_3.Axis4.Acceleration',
 'RB_3.Axis4.Deceleration',
 'RB_3.Axis4.PositionLowerLimit',
 'RB_3.Axis4.PositionUpperLimit',
 'RB_3.Axis4.TargetSpeed',
 'RB_3.Axis5.Acceleration',
 'RB_3.Axis5.Deceleration',
 'RB_3.Axis5.PositionLowerLimit',
 'RB_3.Axis5.PositionUpperLimit',
 'RB_3.Axis5.TargetSpeed',
 'RB_3.Axis6.Acceleration',
 'RB_3.Axis6.Deceleration',
 'RB_3.Axis6.PositionLowerLimit',
 'RB_3.Axis6.PositionUpperLimit',
 'RB_3.Axis6.TargetSpeed',
 'RB_3.ProcessTime',
 'RB_4.Axis1.Acceleration',
 'RB_4.Axis1.Deceleration',
 'RB_4.Axis1.PositionLowerLimit',
 'RB_4.Axis1.PositionUpperLimit',
 'RB_4.Axis1.TargetSpeed',
 'RB_4.Axis2.Acceleration',
 'RB_4.Axis2.Deceleration',
 'RB_4.Axis2.PositionLowerLimit',
 'RB_4.Axis2.PositionUpperLimit',
 'RB_4.Axis2.TargetSpeed',
 'RB_4.Axis3.Acceleration',
 'RB_4.Axis3.Deceleration',
 'RB_4.Axis3.PositionLowerLimit',
 'RB_4.Axis3.PositionUpperLimit',
 'RB_4.Axis3.TargetSpeed',
 'RB_4.Axis4.Acceleration',
 'RB_4.Axis4.Deceleration',
 'RB_4.Axis4.PositionLowerLimit',
 'RB_4.Axis4.PositionUpperLimit',
 'RB_4.Axis4.TargetSpeed',
 'RB_4.Axis5.Acceleration',
 'RB_4.Axis5.Deceleration',
 'RB_4.Axis5.PositionLowerLimit',
 'RB_4.Axis5.PositionUpperLimit',
 'RB_4.Axis5.TargetSpeed',
 'RB_4.Axis6.Acceleration',
 'RB_4.Axis6.Deceleration',
 'RB_4.Axis6.PositionLowerLimit',
 'RB_4.Axis6.PositionUpperLimit',
 'RB_4.Axis6.TargetSpeed',
 'RB_4.ProcessTime',
 'RB_5.Axis1.Acceleration',
 'RB_5.Axis1.Deceleration',
 'RB_5.Axis1.PositionLowerLimit',
 'RB_5.Axis1.PositionUpperLimit',
 'RB_5.Axis1.TargetSpeed',
 'RB_5.Axis2.Acceleration',
 'RB_5.Axis2.Deceleration',
 'RB_5.Axis2.PositionLowerLimit',
 'RB_5.Axis2.PositionUpperLimit',
 'RB_5.Axis2.TargetSpeed',
 'RB_5.Axis3.Acceleration',
 'RB_5.Axis3.Deceleration',
 'RB_5.Axis3.PositionLowerLimit',
 'RB_5.Axis3.PositionUpperLimit',
 'RB_5.Axis3.TargetSpeed',
 'RB_5.Axis4.Acceleration',
 'RB_5.Axis4.Deceleration',
 'RB_5.Axis4.PositionLowerLimit',
 'RB_5.Axis4.PositionUpperLimit',
 'RB_5.Axis4.TargetSpeed',
 'RB_5.Axis5.Acceleration',
 'RB_5.Axis5.Deceleration',
 'RB_5.Axis5.PositionLowerLimit',
 'RB_5.Axis5.PositionUpperLimit',
 'RB_5.Axis5.TargetSpeed',
 'RB_5.Axis6.Acceleration',
 'RB_5.Axis6.Deceleration',
 'RB_5.Axis6.PositionLowerLimit',
 'RB_5.Axis6.PositionUpperLimit',
 'RB_5.Axis6.TargetSpeed',
 'RB_5.ProcessTime',
 'RB_6.Axis1.Acceleration',
 'RB_6.Axis1.Deceleration',
 'RB_6.Axis1.PositionLowerLimit',
 'RB_6.Axis1.PositionUpperLimit',
 'RB_6.Axis1.TargetSpeed',
 'RB_6.Axis2.Acceleration',
 'RB_6.Axis2.Deceleration',
 'RB_6.Axis2.PositionLowerLimit',
 'RB_6.Axis2.PositionUpperLimit',
 'RB_6.Axis2.TargetSpeed',
 'RB_6.Axis3.Acceleration',
 'RB_6.Axis3.Deceleration',
 'RB_6.Axis3.PositionLowerLimit',
 'RB_6.Axis3.PositionUpperLimit',
 'RB_6.Axis3.TargetSpeed',
 'RB_6.Axis4.Acceleration',
 'RB_6.Axis4.Deceleration',
 'RB_6.Axis4.PositionLowerLimit',
 'RB_6.Axis4.PositionUpperLimit',
 'RB_6.Axis4.TargetSpeed',
 'RB_6.Axis5.Acceleration',
 'RB_6.Axis5.Deceleration',
 'RB_6.Axis5.PositionLowerLimit',
 'RB_6.Axis5.PositionUpperLimit',
 'RB_6.Axis5.TargetSpeed',
 'RB_6.Axis6.Acceleration',
 'RB_6.Axis6.Deceleration',
 'RB_6.Axis6.PositionLowerLimit',
 'RB_6.Axis6.PositionUpperLimit',
 'RB_6.Axis6.TargetSpeed',
 'RB_6.ProcessTime',
 'RC_10.Acceleration',
 'RC_10.CurrentDirection',
 'RC_10.Deceleration',
 'RC_10.Height',
 'RC_10.Length',
 'RC_10.MaximumTorque',
 'RC_10.PE1',
 'RC_10.Resistance',
 'RC_10.RollerDamping',
 'RC_10.TargetSpeed',
 'RC_10.Width',
 'RC_100.Acceleration',
 'RC_100.CurrentDirection',
 'RC_100.Deceleration',
 'RC_100.Height',
 'RC_100.Length',
 'RC_100.MaximumTorque',
 'RC_100.PE1',
 'RC_100.Resistance',
 'RC_100.RollerDamping',
 'RC_100.TargetSpeed',
 'RC_100.Width',
 'RC_101.Acceleration',
 'RC_101.CurrentDirection',
 'RC_101.Deceleration',
 'RC_101.Height',
 'RC_101.Length',
 'RC_101.MaximumTorque',
 'RC_101.PE1',
 'RC_101.Resistance',
 'RC_101.RollerDamping',
 'RC_101.TargetSpeed',
 'RC_101.Width',
 'RC_102.Acceleration',

In [15]:
import json
from pathlib import Path

import pandas as pd

# Change this path to split another scenario.
INPUT_PATH = Path("../data/training/0_0pct_faults_rep_1/")

faults = pd.read_parquet(INPUT_PATH / "faults.parquet")
measurements = pd.read_parquet(INPUT_PATH / "measurements.parquet")
parameters = pd.read_parquet(INPUT_PATH / "parameters.parquet")

In [23]:
measurements["AMP_1.CurrentDirection"].

dtype('O')

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import math
from utils import expand_vector_columns

to_drop = ['emulationRealtime', 'novaRealtime']

# Load dataframe
df = pd.read_parquet(INPUT_PATH).drop(columns=to_drop)

df = expand_vector_columns(df, ["AMR_1.CurrentDirection", "AMR_2.CurrentDirection", "AMR_3.CurrentDirection", "PR_118.X.CurrentForce", "PR_118.Y.CurrentForce", "PR_118.Z.CurrentForce", "PR_7.X.CurrentForce", "PR_7.Y.CurrentForce", "PR_7.Z.CurrentForce"])

# Boolean columns
bool_columns = df.select_dtypes(include="bool").columns
df[bool_columns] = df[bool_columns].astype("float64")

# Basic information
print(df.shape)
display(df.head())
display(df.info())

# Summary statistics
display(df.describe(include="all").T)

# Missing values
display(df.isna().sum().sort_values(ascending=False).to_frame("missing"))

# Separate column types
numeric_cols = df.select_dtypes(include="number").columns
categorical_cols = df.select_dtypes(exclude="number").columns

print(f"Numeric columns: {len(numeric_cols)}")
print(f"Categorical columns: {len(categorical_cols)}")

(36000, 4568)

,simulationTime,AMP_1.Acceleration,AMP_1.CurrentAcceleration,AMP_1.CurrentDirection,AMP_1.CurrentI,AMP_1.CurrentSpeed,AMP_1.CurrentState,AMP_1.Deceleration,AMP_1.ElectricPower,AMP_1.EmergencyStop,...,PR_118.Z.CurrentForce.Z,PR_7.X.CurrentForce.X,PR_7.X.CurrentForce.Y,PR_7.X.CurrentForce.Z,PR_7.Y.CurrentForce.X,PR_7.Y.CurrentForce.Y,PR_7.Y.CurrentForce.Z,PR_7.Z.CurrentForce.X,PR_7.Z.CurrentForce.Y,PR_7.Z.CurrentForce.Z
0,0.0,2.5,0.0,Reverse,0.0,0.0,0.0,2.5,0.0,0.0,...,0.000000,0.000000,0.0,-0.000000,-0.000000e+00,0.000000,0.000000e+00,0.0,0.0,0.000000
1,0.1,2.5,0.0,Reverse,0.0,0.0,0.0,2.5,0.0,0.0,...,11.968736,-12.262894,0.0,0.000062,-6.266094e-08,107.650734,8.397861e-13,0.0,0.0,12.046914
2,0.2,2.5,0.0,Reverse,0.0,0.0,0.0,2.5,0.0,0.0,...,11.967810,-12.270333,0.0,0.000062,-6.265708e-08,107.644104,8.397344e-13,0.0,0.0,12.050496
3,0.3,2.5,0.0,Reverse,0.0,0.0,0.0,2.5,0.0,0.0,...,11.967776,-12.270446,0.0,0.000062,-6.265699e-08,107.643940,8.397331e-13,0.0,0.0,12.050534
4,0.4,2.5,0.0,Reverse,0.0,0.0,0.0,2.5,0.0,0.0,...,71.288330,-39.778700,0.0,0.000200,-2.154451e-07,370.132140,2.887410e-12,0.0,0.0,39.562280

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36000 entries, 0 to 35999
Columns: 4568 entries, simulationTime to PR_7.Z.CurrentForce.Z
dtypes: float64(4229), object(339)
memory usage: 1.2+ GB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
simulationTime,36000.0,NaN,NaN,NaN,1799.95,1039.244918,0.0,899.975,1799.95,2699.925,3599.9
AMP_1.Acceleration,36000.0,NaN,NaN,NaN,2.5,0.0,2.5,2.5,2.5,2.5,2.5
AMP_1.CurrentAcceleration,36000.0,NaN,NaN,NaN,0.021528,0.230992,0.0,0.0,0.0,0.0,2.5
AMP_1.CurrentDirection,36000,2,Reverse,21763,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMP_1.CurrentI,36000.0,NaN,NaN,NaN,0.000178,0.002271,0.0,0.0,0.0,0.0,0.040445
...,...,...,...,...,...,...,...,...,...,...,...
PR_7.Y.CurrentForce.Y,36000.0,NaN,NaN,NaN,130.83445,84.45058,-700.0,108.30125,118.03948,127.48614,700.0
PR_7.Y.CurrentForce.Z,36000.0,NaN,NaN,NaN,0.0,0.0,-0.0,0.0,0.0,0.0,0.0
PR_7.Z.CurrentForce.X,36000.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PR_7.Z.CurrentForce.Y,36000.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PR_7.Z.CurrentForce.Z,36000.0,NaN,NaN,NaN,1.504004,26.426381,-611.6008,-12.101483,12.349925,13.731211,714.42426

                           missing
simulationTime                   0
AMP_1.Acceleration               0
AMP_1.CurrentAcceleration        0
AMP_1.CurrentDirection           0
AMP_1.CurrentI                   0
...                            ...
PR_7.Y.CurrentForce.Y            0
PR_7.Y.CurrentForce.Z            0
PR_7.Z.CurrentForce.X            0
PR_7.Z.CurrentForce.Y            0
PR_7.Z.CurrentForce.Z            0

[4568 rows x 1 columns]

Numeric columns: 4229
Categorical columns: 339

In [ ]:
print([c for c in data.columns if c.startswith("RC_8.")])

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Signals to plot
cols = [
    'CurrentAcceleration',
    'CurrentI',
    'CurrentSpeed',
    'CurrentState',
    'ElectricPower'
]

# Same color for the same signal in RC_8 and RC_9
colors = {
    'CurrentAcceleration': 'blue',
    'CurrentI': 'red',
    'CurrentSpeed': 'green',
    'CurrentState': 'orange',
    'ElectricPower': 'purple'
}

# Points 400–460 inclusive
plot_data = data.iloc[400:461]

# Create two subplots
fig = make_subplots(
    rows=2,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.01
)

# Plot RC_8 and RC_9
for col in cols:
    for rc, row in [('RC_8', 1), ('RC_9', 2)]:

        values = plot_data[f'{rc}.{col}']

        # Min-max normalization to 0–1
        min_val = values.min()
        max_val = values.max()

        if max_val != min_val:
            normalized = (values - min_val) / (max_val - min_val)
        else:
            normalized = values * 0

        fig.add_trace(
            go.Scatter(
                x=plot_data.index,
                y=normalized,
                name=f'{rc}.{col}',
                mode='lines+markers',
                line=dict(
                    color=colors[col],
                    width=3
                ),
                marker=dict(
                    size=5
                )
            ),
            row=row,
            col=1
        )

# Y-axis labels and range
fig.update_yaxes(
    title_text="RC_8",
    range=[0, 1.1],
    row=1,
    col=1
)

fig.update_yaxes(
    title_text="RC_9",
    range=[0, 1.1],
    row=2,
    col=1
)

# Layout
fig.update_layout(
    height=500,
    hovermode="x unified",
    margin=dict(
        b=100
    ),
    legend=dict(
        orientation="h",
        yanchor="top",
        y=-0.15,
        xanchor="center",
        x=0.5
    )
)

fig.show()

In [4]:



if not (PROJECT_ROOT / 'data').is_dir():
    PROJECT_ROOT = PROJECT_ROOT.parent
if not (PROJECT_ROOT / 'data').is_dir():
    raise FileNotFoundError(
        'Run this notebook from the repository root or notebooks directory.'
    )

# Change this path to split another scenario.
INPUT_PATH = PROJECT_ROOT / 'data' / 'training' / '0_0pct_faults_rep_1.parquet'
SCENARIO_PATH = (
    PROJECT_ROOT
    / 'scenarios'
    / INPUT_PATH.parent.name
    / f'{INPUT_PATH.stem}.json'
)
OUTPUT_DIR = INPUT_PATH.with_suffix('')

data = pd.read_parquet(INPUT_PATH)
scenario = json.loads(SCENARIO_PATH.read_text(encoding='utf-8'))
scenario_id = str(scenario['scenario']['id'])

In [5]:
data.columns

Index(['emulationRealtime', 'novaRealtime', 'simulationTime',
       'AMP_1.Acceleration', 'AMP_1.CurrentAcceleration',
       'AMP_1.CurrentDirection', 'AMP_1.CurrentI', 'AMP_1.CurrentSpeed',
       'AMP_1.CurrentState', 'AMP_1.Deceleration',
       ...
       'RS_6.MotorFault', 'RS_6.PE1', 'RS_6.PeDefect',
       'RS_6.PeWrongCalibration', 'RS_6.Resistance', 'RS_6.RollerDamping',
       'RS_6.SpeedCalibrationFault', 'RS_6.TargetSpeed', 'RS_6.WearFault',
       'RS_6.Width'],
      dtype='object', length=4552)

## Dataset split

The exports use the required common keys: `scenario_id`, `simulation_step`, and `simulation_time`. Fault labels are taken from the matching scenario actions rather than included in the deployable measurement matrix. Oracle states are only accepted from explicitly named `oracle` or `hidden` namespaces, which prevents unmarked simulator fields from leaking into measurements.

In [ ]:
KEY_COLUMNS = ['scenario_id', 'simulation_step', 'simulation_time']
SOURCE_KEY_COLUMNS = {
    'scenarioId',
    'scenario_id',
    'simulationStep',
    'simulation_step',
    'simulationTime',
    'simulation_time',
}
TRACE_COLUMN_RENAMES = {
    'emulationRealtime': 'emulation_realtime',
    'novaRealtime': 'nova_realtime',
    'runId': 'run_id',
}
PARAMETER_SUFFIXES = frozenset(
    {
        'Acceleration',
        'Deceleration',
        'Length',
        'Mass',
        'MaximumForce',
        'MaximumTorque',
        'PositionLowerLimit',
        'PositionUpperLimit',
        'ProcessTime',
        'Resistance',
        'RollerDamping',
        'Width',
    }
)

if data.empty:
    raise ValueError(f'Cannot split an empty dataset: {INPUT_PATH}')

component_type_knowledge = json.loads(
    (PROJECT_ROOT / 'component_type_knowledge.json').read_text(encoding='utf-8')
)
FAULT_PROPERTIES = frozenset(
    fault['name']
    for component in component_type_knowledge.values()
    for fault in component['faultTypes']
)


def suffix(column: str) -> str:
    return column.rsplit('.', 1)[-1]


def is_oracle_column(column: str) -> bool:
    normalized = column.casefold()
    return normalized.startswith(('oracle.', 'hidden.')) or any(
        marker in normalized for marker in ('.oracle.', '.hidden.')
    )


source_time_column = next(
    (column for column in ('simulationTime', 'simulation_time') if column in data),
    None,
)
if source_time_column is None:
    raise KeyError('The source dataset must contain simulationTime or simulation_time.')

source_step_column = next(
    (column for column in ('simulationStep', 'simulation_step') if column in data),
    None,
)
simulation_steps = (
    data[source_step_column].to_numpy()
    if source_step_column is not None
    else range(len(data))
)
sample_keys = pd.DataFrame(
    {
        'scenario_id': scenario_id,
        'simulation_step': simulation_steps,
        'simulation_time': pd.to_numeric(data[source_time_column]),
    }
)

fault_columns = [
    column for column in data if suffix(column) in FAULT_PROPERTIES
]
oracle_columns = [column for column in data if is_oracle_column(column)]
parameter_candidates = [
    column
    for column in data
    if column not in fault_columns
    and column not in oracle_columns
    and suffix(column) in PARAMETER_SUFFIXES
]
parameter_columns = [
    column
    for column in parameter_candidates
    if data[column].nunique(dropna=False) == 1
]
trace_columns = [column for column in TRACE_COLUMN_RENAMES if column in data]

excluded_columns = (
    SOURCE_KEY_COLUMNS.intersection(data.columns)
    | set(trace_columns)
    | set(fault_columns)
    | set(oracle_columns)
    | set(parameter_columns)
)
measurement_columns = [column for column in data if column not in excluded_columns]

split_groups = {
    'fault': set(fault_columns),
    'oracle': set(oracle_columns),
    'parameter': set(parameter_columns),
    'measurement': set(measurement_columns),
}
for group_name, columns in split_groups.items():
    for other_group_name, other_columns in split_groups.items():
        if group_name < other_group_name and columns.intersection(other_columns):
            raise ValueError(
                f'Columns assigned to both {group_name} and {other_group_name}: '
                f'{sorted(columns.intersection(other_columns))}'
            )

dynamic_parameter_candidates = [
    column for column in parameter_candidates if column not in parameter_columns
]
if dynamic_parameter_candidates:
    print(
        'Keeping dynamic configuration candidates in measurements: '
        + ', '.join(dynamic_parameter_candidates)
    )

In [ ]:
def clock_to_seconds(clock: str) -> float:
    parts = [float(part) for part in clock.split(':')]
    if len(parts) == 2:
        minutes, seconds = parts
        return minutes * 60 + seconds
    if len(parts) == 3:
        hours, minutes, seconds = parts
        return hours * 3600 + minutes * 60 + seconds
    raise ValueError(f'Unsupported scenario timestamp: {clock}')


def normalize_action_value(value: object) -> str:
    return str(value).strip().replace(',', '.').casefold()


fault_repair_values = {}
for component in component_type_knowledge.values():
    for fault in component['faultTypes']:
        name = fault['name']
        repair_value = normalize_action_value(fault.get('repairValue', ''))
        if name in fault_repair_values and fault_repair_values[name] != repair_value:
            raise ValueError(f'Conflicting repair values defined for {name}.')
        fault_repair_values[name] = repair_value


def empty_fault_events() -> pd.DataFrame:
    return pd.DataFrame(
        {
            'scenario_id': pd.Series(dtype='string'),
            'simulation_step': pd.Series(dtype='int64'),
            'simulation_time': pd.Series(dtype='float64'),
            'fault_area': pd.Series(dtype='string'),
            'fault_component': pd.Series(dtype='string'),
            'fault_property': pd.Series(dtype='string'),
            'fault_value': pd.Series(dtype='string'),
            'event_type': pd.Series(dtype='string'),
            'fault_active': pd.Series(dtype='bool'),
        }
    )


def build_fault_events() -> pd.DataFrame:
    event_rows = []
    for action in scenario['actions']:
        property_name = action.get('property')
        if property_name not in FAULT_PROPERTIES:
            continue

        fault_value = action.get('value', '')
        event_type = (
            'repair'
            if normalize_action_value(fault_value)
            == fault_repair_values[property_name]
            else 'activation'
        )
        event_rows.append(
            {
                'scenario_id': scenario_id,
                'simulation_time': clock_to_seconds(action['startsAt']),
                'fault_area': action.get('area'),
                'fault_component': action.get('element'),
                'fault_property': property_name,
                'fault_value': str(fault_value),
                'event_type': event_type,
                'fault_active': event_type == 'activation',
            }
        )

    if not event_rows:
        return empty_fault_events()

    timeline = sample_keys[['simulation_step', 'simulation_time']].sort_values(
        'simulation_time'
    )
    events = pd.DataFrame(event_rows).sort_values('simulation_time')
    if (
        events['simulation_time'].lt(timeline['simulation_time'].min()).any()
        or events['simulation_time'].gt(timeline['simulation_time'].max()).any()
    ):
        raise ValueError('A fault event falls outside the recorded simulation time range.')

    events = pd.merge_asof(
        events,
        timeline,
        on='simulation_time',
        direction='nearest',
    )
    return events[
        [
            'scenario_id',
            'simulation_step',
            'simulation_time',
            'fault_area',
            'fault_component',
            'fault_property',
            'fault_value',
            'event_type',
            'fault_active',
        ]
    ].reset_index(drop=True)


trace_data = data[trace_columns].rename(columns=TRACE_COLUMN_RENAMES)
measurements = pd.concat(
    [sample_keys, trace_data.reset_index(drop=True), data[measurement_columns]],
    axis=1,
)
oracle_states = pd.concat([sample_keys, data[oracle_columns]], axis=1)
parameters = pd.concat(
    [
        sample_keys.iloc[[0]].reset_index(drop=True),
        data[parameter_columns].iloc[[0]].reset_index(drop=True),
    ],
    axis=1,
)
fault_events = build_fault_events()

if not oracle_columns:
    print(
        'No explicitly named oracle-state columns were found; '
        'oracle_states.parquet contains only the common keys.'
    )

tables = {
    'measurements': measurements,
    'oracle_states': oracle_states,
    'parameters': parameters,
    'fault_events': fault_events,
}
for table_name, table in tables.items():
    missing_keys = set(KEY_COLUMNS).difference(table.columns)
    if missing_keys:
        raise ValueError(f'{table_name} is missing common keys: {sorted(missing_keys)}')

if set(measurement_columns).intersection(fault_columns + oracle_columns):
    raise ValueError('Measurements contain fault or oracle columns.')

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
for table_name, table in tables.items():
    table.to_parquet(OUTPUT_DIR / f'{table_name}.parquet', index=False)

pd.DataFrame(
    {
        'rows': {table_name: len(table) for table_name, table in tables.items()},
        'columns': {
            table_name: len(table.columns) for table_name, table in tables.items()
        },
        'path': {
            table_name: str(OUTPUT_DIR / f'{table_name}.parquet')
            for table_name in tables
        },
    }
)